# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Position Controllers --------------------------------------- 1.7
wheel0_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel0_joint
  pid: {p: 4.0, i: 0.5, d: 0.0}
wheel1_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel1_joint
  pid: {p: 4.0, i: 0.5, d: 0.0}
wheel2_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel2_joint
  pid: {p: 4.0, i: 0.5, d: 0.0}
